trigger:
  branches:
    include:
      - main

pool:
  name: terraform-hubspoke-pool

variables:
  - group: terraform-hubspoke-grp
  - name: TF_VERSION
    value: '1.6.6'
  - name: backendServiceArm
    value: 'terraform-hubspoke-connection'

steps:
# Install specified Terraform version (Jason Johnson's extension)
- task: JasonBJohnson.azure-pipelines-tasks-terraform.terraform-installer.TerraformInstaller@1
  inputs:
    terraformVersion: $(TF_VERSION)

# Azure CLI login verification
- task: AzureCLI@2
  inputs:
    azureSubscription: $(backendServiceArm)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "##[section]Verifying Azure CLI authentication..."
      az account show

# Terraform Init with backend configuration
- task: JasonBJohnson.azure-pipelines-tasks-terraform.terraform-task.TerraformTask@4
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: $(backendServiceArm)
    backendAzureRmResourceGroupName: 'PTutorial-rg'
    backendAzureRmStorageAccountName: 'ptutorial123'
    backendAzureRmContainerName: 'ptstate'
    backendAzureRmKey: 'terraform.tfstate'

# Terraform Plan
- task: JasonBJohnson.azure-pipelines-tasks-terraform.terraform-task.TerraformTask@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    backendServiceArm: $(backendServiceArm)

# Terraform Apply with auto-approve
- task: JasonBJohnson.azure-pipelines-tasks-terraform.terraform-task.TerraformTask@4
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    backendServiceArm: $(backendServiceArm)
    args: '-auto-approve'
