# Terraform Init
- task: TerraformCLI@0
  displayName: 'Terraform Init'
  inputs:
    command: 'init'
    provider: 'azurerm'
    backendServiceArm: $(backendServiceArm)
    backendAzureRmResourceGroupName: 'PTutorial-rg'
    backendAzureRmStorageAccountName: 'ptutorial123'
    backendAzureRmContainerName: 'ptstate'
    backendAzureRmKey: 'terraform.tfstate'
    workingDirectory: '.'

# Terraform Plan (save to file)
- task: TerraformCLI@0
  displayName: 'Terraform Plan'
  inputs:
    command: 'plan'
    provider: 'azurerm'
    environmentServiceNameAzureRM: $(backendServiceArm)
    workingDirectory: '.'
    args: '-out=tfplan'

# Publish the plan file
- task: PublishPipelineArtifact@1
  displayName: 'Publish Terraform Plan Artifact'
  inputs:
    targetPath: '$(System.DefaultWorkingDirectory)/tfplan'
    artifact: 'tfplan'
    publishLocation: 'pipeline'

# Terraform Apply (use tfplan)
- task: TerraformCLI@0
  displayName: 'Terraform Apply'
  inputs:
    command: 'apply'
    provider: 'azurerm'
    args: 'tfplan -auto-approve'
    workingDirectory: '.'
