trigger:
  branches:
    include:
      - main  # Adjust if your default branch is different

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: terraform-hubspoke-grp
  TF_VERSION: '1.6.6'
  backendServiceArm: 'terraform-hubspoke-connection'
  azureSubscription: 'terraform-hubspoke-connection'

steps:
# Install Terraform
- task: TerraformInstaller@1
  inputs:
    terraformVersion: $(TF_VERSION)

# Azure Login
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      echo "##[section]Verifying Azure CLI authentication..."
      az account show

# Terraform Init
- task: TerraformTaskV4@4
  displayName: 'Terraform Init'
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: $(backendServiceArm)
    backendAzureRmResourceGroupName: 'PTutorial'           # ✅ Replace with your backend RG name
    backendAzureRmStorageAccountName: 'ptutorial123'        # ✅ Replace with your backend storage account
    backendAzureRmContainerName: 'ptstate'
    backendAzureRmKey: 'terraform.tfstate'

# Terraform Plan
- task: TerraformTaskV4@4
  displayName: 'Terraform Plan'
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: $(backendServiceArm)

# Terraform Apply
- task: TerraformTaskV4@4
  displayName: 'Terraform Apply'
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: $(backendServiceArm)
    args: '-auto-approve'
