trigger:
  branches:
    include:
      - main

pool:
  name: terraform-hubspoke-pool

variables:
  - group: terraform-hubspoke-grp
  - name: TF_VERSION
    value: '1.6.6'
  - name: backendServiceArm
    value: 'terraform-hubspoke-connection'

steps:
# Install specified Terraform version
- task: TerraformInstaller@0
  inputs:
    terraformVersion: $(TF_VERSION)

# Terraform Init with Azure RM backend config
- task: TerraformCLI@0
  displayName: 'Terraform Init'
  inputs:
    command: 'init'
    provider: 'azurerm'
    backendServiceArm: $(backendServiceArm)
    backendAzureRmResourceGroupName: 'PTutorial-rg'
    backendAzureRmStorageAccountName: 'ptutorial123'
    backendAzureRmContainerName: 'ptstate'
    backendAzureRmKey: 'terraform.tfstate'

# Terraform Plan
- task: TerraformCLI@0
  displayName: 'Terraform Plan'
  inputs:
    command: 'plan'
    provider: 'azurerm'

# Terraform Apply (auto approve)
- task: TerraformCLI@0
  displayName: 'Terraform Apply'
  inputs:
    command: 'apply'
    provider: 'azurerm'
    args: '-auto-approve'
