#cloud-config

package_update: true
package_upgrade: true
packages:
  - apache2

write_files:
  - path: /etc/resolv.conf
    content: |
      nameserver 10.0.2.4
      search localdomain

runcmd:
  - systemctl restart systemd-resolved || true
  - systemctl enable apache2
  - systemctl start apache2
  - echo "<h1>Hello from web-vm-1 via cloud-init</h1>" > /var/www/html/index.html
