#cloud-config

package_update: true
package_upgrade: true
packages:
  - apache2

write_files:
  - path: /etc/resolv.conf
    content: |
      nameserver 10.0.2.4
      search localdomain

  - path: /etc/sysctl.d/99-ipforward.conf
    content: |
      net.ipv4.ip_forward = 1

runcmd:
  - sysctl --system
  - systemctl restart systemd-resolved || true
  - iptables -P FORWARD ACCEPT
  - systemctl enable apache2
  - systemctl start apache2
  - echo "<h1>Hello from web-vm-1 via cloud-init</h1>" > /var/www/html/index.html
